# Generated by Django 4.2.11 on 2024-05-16 08:20

import django.core.validators
from django.db import migrations, models
import vapeshop.validation


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(18)], verbose_name='Вік'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=13, validators=[vapeshop.validation.validate_phone_length], verbose_name='Номер телефону'),
        ),
    ]
