# Generated by Django 4.2.11 on 2024-04-14 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id'], 'verbose_name': 'категорія', 'verbose_name_plural': 'категорії'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'товар', 'verbose_name_plural': 'товар'},
        ),
    ]
