# Generated by Django 4.2.11 on 2024-05-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['status', '-created_at'], 'verbose_name': 'замовлення', 'verbose_name_plural': 'замовлення'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, 'Створюється'), (1, 'В обробці'), (2, 'Відправлено'), (3, 'Доставлено'), (4, 'Скасовано')], default=0),
        ),
    ]
