# Generated by Django 4.2.11 on 2024-05-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_order_options_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Створюється'), (1, 'В обробці'), (2, 'Відправлено'), (3, 'Доставлено'), (4, 'Скасовано')], default=0),
        ),
    ]
